name = "PhysiCellXMLRules"
uuid = "bad69253-e2d7-49f9-a0cf-2fd158c7c32b"
authors = ["Daniel Bergman <danielrbergman@gmail.com> and contributors"]
version = "0.0.9"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
LightXML = "0.9.1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
